import { 
  int, 
  mysqlEnum, 
  mysqlTable, 
  text, 
  timestamp, 
  varchar,
  decimal,
  json,
  boolean
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow with Supabase Auth integration.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  supabaseId: varchar("supabaseId", { length: 64 }).notNull().unique(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  name: text("name"),
  avatar: text("avatar"),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  plan: mysqlEnum("plan", ["free", "growth", "scale"]).default("free").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Businesses owned by users - core entity for the platform
 */
export const businesses = mysqlTable("businesses", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  type: varchar("type", { length: 100 }),
  city: varchar("city", { length: 100 }),
  website: varchar("website", { length: 255 }),
  whatsappNumber: varchar("whatsappNumber", { length: 20 }),
  mainOffer: text("mainOffer"),
  targetCustomer: text("targetCustomer"),
  brandTone: varchar("brandTone", { length: 100 }),
  logo: text("logo"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Business = typeof businesses.$inferSelect;
export type InsertBusiness = typeof businesses.$inferInsert;

/**
 * Growth profiles generated by Onboarding Agent
 */
export const growthProfiles = mysqlTable("growthProfiles", {
  id: int("id").autoincrement().primaryKey(),
  businessId: int("businessId").notNull(),
  idealCustomer: text("idealCustomer"),
  winningHooks: json("winningHooks").$type<string[]>(),
  bestCreativeFormat: varchar("bestCreativeFormat", { length: 100 }),
  recommendedTargeting: json("recommendedTargeting").$type<Record<string, unknown>>(),
  competitorWeakness: text("competitorWeakness"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type GrowthProfile = typeof growthProfiles.$inferSelect;
export type InsertGrowthProfile = typeof growthProfiles.$inferInsert;

/**
 * Campaigns managed by users
 */
export const campaigns = mysqlTable("campaigns", {
  id: int("id").autoincrement().primaryKey(),
  businessId: int("businessId").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  status: mysqlEnum("status", ["active", "testing", "paused", "completed"]).default("testing").notNull(),
  goal: varchar("goal", { length: 100 }),
  platform: varchar("platform", { length: 50 }).default("meta"),
  budget: decimal("budget", { precision: 10, scale: 2 }).default("0"),
  spend: decimal("spend", { precision: 10, scale: 2 }).default("0"),
  leads: int("leads").default(0),
  cpl: decimal("cpl", { precision: 10, scale: 2 }).default("0"),
  roas: decimal("roas", { precision: 5, scale: 2 }).default("0"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Campaign = typeof campaigns.$inferSelect;
export type InsertCampaign = typeof campaigns.$inferInsert;

/**
 * Ad creatives generated by Creative Agent
 */
export const adCreatives = mysqlTable("adCreatives", {
  id: int("id").autoincrement().primaryKey(),
  campaignId: int("campaignId").notNull(),
  headline: varchar("headline", { length: 255 }).notNull(),
  primaryText: text("primaryText"),
  cta: varchar("cta", { length: 100 }),
  hook: text("hook"),
  targetAudience: text("targetAudience"),
  format: varchar("format", { length: 50 }),
  performance: json("performance").$type<Record<string, unknown>>(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AdCreative = typeof adCreatives.$inferSelect;
export type InsertAdCreative = typeof adCreatives.$inferInsert;

/**
 * Content calendar for Instagram scheduling
 */
export const contentCalendar = mysqlTable("contentCalendar", {
  id: int("id").autoincrement().primaryKey(),
  businessId: int("businessId").notNull(),
  type: varchar("type", { length: 50 }),
  caption: text("caption"),
  imagePrompt: text("imagePrompt"),
  imageUrl: text("imageUrl"),
  scheduledAt: timestamp("scheduledAt"),
  status: mysqlEnum("status", ["draft", "scheduled", "published"]).default("draft").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ContentPost = typeof contentCalendar.$inferSelect;
export type InsertContentPost = typeof contentCalendar.$inferInsert;

/**
 * Weekly reports generated by Reporting Agent
 */
export const weeklyReports = mysqlTable("weeklyReports", {
  id: int("id").autoincrement().primaryKey(),
  businessId: int("businessId").notNull(),
  week: varchar("week", { length: 20 }).notNull(),
  leads: int("leads").default(0),
  spend: decimal("spend", { precision: 10, scale: 2 }).default("0"),
  roas: decimal("roas", { precision: 5, scale: 2 }).default("0"),
  bestAd: varchar("bestAd", { length: 255 }),
  cpl: decimal("cpl", { precision: 10, scale: 2 }).default("0"),
  actions: int("actions").default(0),
  report: text("report"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type WeeklyReport = typeof weeklyReports.$inferSelect;
export type InsertWeeklyReport = typeof weeklyReports.$inferInsert;

/**
 * ZOE optimization actions logged for activity feed
 */
export const zoeActions = mysqlTable("zoeActions", {
  id: int("id").autoincrement().primaryKey(),
  businessId: int("businessId").notNull(),
  type: varchar("type", { length: 100 }).notNull(),
  title: text("title"),
  description: text("description"),
  icon: varchar("icon", { length: 50 }),
  isPulse: boolean("isPulse").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ZoeAction = typeof zoeActions.$inferSelect;
export type InsertZoeAction = typeof zoeActions.$inferInsert;
